version: 2
jobs:
  build:
    docker:
      - image: ethereum/cpp-build-env
    working_directory: ~/cpp-ethereum
    steps:
      - checkout

      - run:
          name: "Init submodules"
          command: git submodule update --init

      - cache-restore:
          name: "Restore dependencies cache"
          key: deps-2-{{ checksum "cmake/ProjectJsonRpcCpp.cmake" }}

      - run:
          name: "Configure"
          command: |
            mkdir build && cd build
            cmake .. -DCOVERAGE=ON

      - run:
          name: "Upload Hunter cache"
          command: |
            cmake --build build --target hunter_upload_cache

      - run:
          name: "Build"
          command: |
            cmake --build build -- -j4

      - cache-save:
          name: "Save dependencies cache"
          key: deps-2-{{ checksum "cmake/ProjectJsonRpcCpp.cmake" }}
          paths:
            - deps

      - store_artifacts:
          path: build/eth/eth
          destination: eth

      - cache-restore:
          name: "Restore Ethash DAG file"
          key: ethash-dag0

      - run:
          name: "Test"
          pwd: ~/cpp-ethereum/build
          command: |
            export ETHEREUM_TEST_PATH=~/cpp-ethereum/test/jsontests
            export TMPDIR=/dev/shm
            test/testeth -t BlockchainTests &
            test/testeth -t StateTestsGeneral &
            test/testeth -t 'KeyStore:Crypto:KeyManagerTests' &
            test/testeth -t '!BlockchainTests:!StateTestsGeneral:!KeyStore:!Crypto:!KeyManagerTests' &
            wait

      - cache-save:
          name: "Save Ethash DAG file"
          key: ethash-dag0
          paths:
            - ~/.ethash/full-R23-0000000000000000

      - run:
          name: "Code coverage"
          pwd: ~/cpp-ethereum/build
          command: |
            cmake --build . --target coverage.data
            bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/d8016a07d67d813f98afdbaf98dc4f46d9806118/codecov) -X fix -f coverage.data
